# Generated by Django 3.1.7 on 2021-04-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('1', '高'), ('2', '中'), ('3', '低')], max_length=30)),
            ],
        ),
    ]
