# Generated by Django 3.1.7 on 2021-04-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20210331_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='priority',
            field=models.CharField(choices=[('1', '高'), ('2', '中'), ('3', '低')], default='', max_length=30),
        ),
    ]
