# Generated by Django 3.1.7 on 2021-04-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_list_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='priority',
            field=models.CharField(choices=[('1', '高'), ('2', '中'), ('3', '低')], max_length=30),
        ),
    ]
