# Generated by Django 3.1.7 on 2021-04-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_auto_20210420_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('1', '高'), ('2', '中'), ('3', '低')], max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='list',
            name='priority',
        ),
    ]
